import { useState } from 'react';
import { useNavigate } from 'react-router-dom';

import { createProposal, hashDocument } from '../api';
import type { CreateProposalInput } from '../types';

function defaultExpiresAt(): string {
  return new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString();
}

function formDefaults(): CreateProposalInput {
  return {
    targetSignatures: 1000,
    expiresAt: defaultExpiresAt(),
    proposal: {
      title: '',
      promoter: '',
      jurisdiction: '',
      summary: '',
      legalStatement: '',
      fullTextURL: '',
      fullTextSHA256: ''
    }
  };
}

export function CreateProposalPage(): JSX.Element {
  const navigate = useNavigate();
  const [form, setForm] = useState<CreateProposalInput>(formDefaults());
  const [submitting, setSubmitting] = useState(false);
  const [hashing, setHashing] = useState(false);
  const [error, setError] = useState('');

  async function computeHash(url: string): Promise<void> {
    if (!url) return;
    setHashing(true);
    setError('');
    try {
      const { sha256 } = await hashDocument(url);
      setForm((prev) => ({ ...prev, proposal: { ...prev.proposal, fullTextSHA256: sha256 } }));
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : 'Could not compute document hash');
    } finally {
      setHashing(false);
    }
  }

  async function handleSubmit(event: React.FormEvent<HTMLFormElement>): Promise<void> {
    event.preventDefault();
    setSubmitting(true);
    setError('');

    try {
      const created = await createProposal(form);
      navigate(`/proposals/${encodeURIComponent(created.requestId)}`);
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : 'Could not create proposal');
    } finally {
      setSubmitting(false);
    }
  }

  return (
    <section className="container">
      <div className="form-shell">
        <h2>Create a new proposal</h2>
        <p>Only organizer-facing fields are required here. Technical metadata is generated by the backend.</p>

        <form onSubmit={handleSubmit} className="proposal-form">
          <div className="grid two">
            <label>
              Target signatures
              <input
                type="number"
                min={0}
                placeholder="50000"
                value={form.targetSignatures}
                onChange={(e) => setForm({ ...form, targetSignatures: Number(e.target.value || 0) })}
                required
              />
            </label>
            <label>
              Expires at (ISO)
              <input
                placeholder="2027-12-31T23:59:59Z"
                value={form.expiresAt ?? ''}
                onChange={(e) => setForm({ ...form, expiresAt: e.target.value || undefined })}
              />
            </label>
          </div>

          <h3>Proposal details</h3>
          <div className="grid two">
            <label>
              Title
              <input
                placeholder="Legislative proposal for sustainable public housing"
                value={form.proposal.title}
                onChange={(e) => setForm({ ...form, proposal: { ...form.proposal, title: e.target.value } })}
                required
              />
            </label>
            <label>
              Promoter
              <input
                placeholder="Citizen Committee for Housing Rights"
                value={form.proposal.promoter}
                onChange={(e) => setForm({ ...form, proposal: { ...form.proposal, promoter: e.target.value } })}
                required
              />
            </label>
            <label>
              Jurisdiction
              <input
                placeholder="Catalonia"
                value={form.proposal.jurisdiction}
                onChange={(e) => setForm({ ...form, proposal: { ...form.proposal, jurisdiction: e.target.value } })}
                required
              />
            </label>
            <label>
              Full text URL
              <input
                type="url"
                placeholder="https://example.org/proposals/housing-law.pdf"
                value={form.proposal.fullTextURL}
                onChange={(e) => setForm({ ...form, proposal: { ...form.proposal, fullTextURL: e.target.value } })}
                onBlur={(e) => {
                  if (e.target.value && !form.proposal.fullTextSHA256) {
                    computeHash(e.target.value);
                  }
                }}
                required
              />
            </label>
            <label>
              Full text SHA-256 (base64)
              <span className="input-with-btn">
                <input
                  placeholder={hashing ? 'Computing hash...' : 'Auto-computed from document URL'}
                  value={form.proposal.fullTextSHA256}
                  onChange={(e) => setForm({ ...form, proposal: { ...form.proposal, fullTextSHA256: e.target.value } })}
                  required
                />
                <button
                  type="button"
                  className="btn btn-secondary btn-sm"
                  disabled={hashing || !form.proposal.fullTextURL}
                  onClick={() => computeHash(form.proposal.fullTextURL)}
                >
                  {hashing ? 'Computing...' : 'Calculate'}
                </button>
              </span>
            </label>
            <label className="full">
              Summary
              <textarea
                placeholder="This proposal introduces mandatory minimum social housing quotas and stronger tenant protections."
                value={form.proposal.summary}
                onChange={(e) => setForm({ ...form, proposal: { ...form.proposal, summary: e.target.value } })}
                required
              />
            </label>
            <label className="full">
              Legal statement
              <textarea
                placeholder="By signing this request with a valid official certificate, I formally support this legislative proposal."
                value={form.proposal.legalStatement}
                onChange={(e) => setForm({ ...form, proposal: { ...form.proposal, legalStatement: e.target.value } })}
                required
              />
            </label>
          </div>

          {error ? <p className="error-box">{error}</p> : null}

          <div className="form-actions">
            <button className="btn btn-primary" type="submit" disabled={submitting}>
              {submitting ? 'Creating proposal...' : 'Create proposal'}
            </button>
          </div>
        </form>
      </div>
    </section>
  );
}
