import { existsSync, readFileSync, readdirSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { X509Certificate } from 'node:crypto';

export interface TrustStore {
  roots: X509Certificate[];
  intermediates: X509Certificate[];
}

const CA_CERTS_DIR = resolve(
  fileURLToPath(import.meta.url),
  '..',
  'ca-certs'
);

// Test CA certificate generated by test/gen_certs_test.go
// (TestGenerateIDCatCertWithAllFields).  Loaded automatically when
// ALLOW_TEST_CERTS=true so the full issuer-check + chain-verification
// flow can be exercised with test certificates.
const TEST_CA_PEM = resolve(
  fileURLToPath(import.meta.url),
  '..', '..', '..', '..', '..', 'test', 'certs', 'ec-ciutadania-test-ca.pem'
);

function loadPemsFromDir(dir: string, roots: X509Certificate[], intermediates: X509Certificate[]): void {
  const files = readdirSync(dir).filter((f) => f.endsWith('.pem'));
  for (const file of files) {
    loadPemsFromFile(join(dir, file), roots, intermediates);
  }
}

function loadPemsFromFile(path: string, roots: X509Certificate[], intermediates: X509Certificate[]): void {
  const pem = readFileSync(path, 'utf-8');
  const certPems = pem.match(/-----BEGIN CERTIFICATE-----[\s\S]*?-----END CERTIFICATE-----/g);
  if (!certPems) return;

  for (const certPem of certPems) {
    const cert = new X509Certificate(certPem);
    if (cert.subject === cert.issuer) {
      roots.push(cert);
    } else {
      intermediates.push(cert);
    }
  }
}

/**
 * Load all PEM files from the ca-certs directory and classify them
 * as roots (self-signed) or intermediates.
 *
 * When ALLOW_TEST_CERTS=true, the test CA certificate from
 * test/certs/ec-ciutadania-test-ca.pem is also loaded so that the
 * full chain verification flow works with generated test certificates.
 */
export function loadTrustStore(dir: string = CA_CERTS_DIR): TrustStore {
  const roots: X509Certificate[] = [];
  const intermediates: X509Certificate[] = [];

  loadPemsFromDir(dir, roots, intermediates);

  if (process.env.ALLOW_TEST_CERTS && existsSync(TEST_CA_PEM)) {
    loadPemsFromFile(TEST_CA_PEM, roots, intermediates);
    console.log(`Loaded test CA from ${TEST_CA_PEM}`);
  }

  if (roots.length === 0) {
    throw new Error('No root CA certificates found in trust store');
  }

  return { roots, intermediates };
}

/** Singleton trust store instance, loaded once. */
let _store: TrustStore | null = null;

export function getTrustStore(): TrustStore {
  if (!_store) {
    _store = loadTrustStore();
  }
  return _store;
}
